name: CI

on: [push, pull_request]

jobs:
    ci:
        name: Build + Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Build Project
              run: cd sample && ./gradlew :app:assembleDebug && ./gradlew clean && ./gradlew :otherapp:assembleDebug
